<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>E_Commerce.Presistence</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.20" />
    <PackageReference Include="StackExchange.Redis" Version="2.9.32" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\E-Commerce.Service\E-Commerce.Service.csproj" />
    <ProjectReference Include="..\Ecommerce.Infrastructure.Service\Ecommerce.Infrastructure.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Context\DataSeed\brands.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Context\DataSeed\delivery.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Context\DataSeed\products.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Context\DataSeed\types.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
